name:  imageViewer
description:  A sample application

dependencies:
    browser: any
    js: { hosted } 
    html5lib: any
    rikulo_commons: any
    rikulo:
      git: git://github.com/rikulo/rikulo.git

##dependencies:
#  js: any
#  unittest: any
